### ISSUE TITLE
About Training time

### ISSUE THREAD

**Issue by sseunghyuns** [Omni6DPose/GenPose2#3]
Hello! 

How long does it take to train GenPose++?

**Comment by Jiyao06** [comment]
Training GenPose++ on a single NVIDIA RTX 4090 GPU for about four days is reasonable. To reduce training time, consider adjusting batch sizes or learning rates, or employing multi-GPU distributed training.

**Comment by sseunghyuns** [comment]
Thank you for your response! 
I saw the GenPose experiment results in the paper. Does training Omni6DPose with GenPose also take that long?
